### ISSUE TITLE
Evernote, Github and OCWi partial or overlapping materials

### ISSUE THREAD

**Issue by mbdevpl** [wakita/fmcs2015#2]
Konnichiwa again, Sensei,

I hope small suggestions about the course are also welcome.

When I was browsing through materials, I have noticed that:
- on Evernote there is only a portion of materials of the course (tasks, guides and references),
- another portion is on Github (lecture notes, code),
- and on OCWi are only the lecture notes.

It was a little bit confusing for me when I was wondering "how to get all the slides, tasks and other materials for the course?". For example: if the PDF i got from OCWi (under the name `Supplementary document.pdf`) is the same as another PDF I downloaded from Github (e.g. filename `kw23.pdf`).

In the end I think I got it all. On the other hand, I think some of the future students would really like to see all the materials for the course in one place.

**Comment by wakita** [comment]
Hope you are doing well.

Thanks for your comments.  I am sorry but I have just realized about your issue post and another one, too.  Thanks for your feedbacks.  FMCS class has ended due to educational reform and will not be opened again.  Still I take your comment and try to offer single point of visit of my class materials.

Ken
